// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehdwvhsabhamwpgpurqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoZHd2aHNhYmhhbXdwZ3B1cnFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5ODIwMDAsImV4cCI6MjA3MDU1ODAwMH0.swqGhzkkv_4V-c0VT-SWiSvnu_yJGr9677YvPb2BwpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});